project_id = "pnwstilxwpzrjqdwrqay"

[functions.migrate-users]
verify_jwt = false

[functions.licensee-auth]
verify_jwt = false

[functions.licensee-portal-data]
verify_jwt = false

[functions.nfse-emission]
verify_jwt = false

[functions.nfse-consulta]
verify_jwt = false

[functions.nfse-eventos]
verify_jwt = false
